"""
Gurobi-based optimal solver for EV truck routing with charging.

This module provides a deterministic MILP formulation that:
1. Takes a scenario generated by environment reset
2. Computes optimal routes and charging decisions for all trucks
3. Minimizes total travel time while maintaining battery feasibility
4. Respects delivery sequence ordering and charging station capacity
"""

import gurobipy as gp
from gurobipy import GRB
import numpy as np
from typing import Dict, List, Tuple, Optional, Set
import copy
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


class GurobiOptimalPlanner:
    """
    Optimal planner using Gurobi MILP solver with truck decomposition.
    
    Since trucks are independent (operate asynchronously), we solve each truck's
    routing problem separately, which dramatically reduces model size.
    
    Decision Variables (per truck):
    - x[i,j]: Binary, truck travels from node i to node j
    - t[i]: Continuous, arrival time at node i
    - b[i]: Continuous, battery level upon arrival at node i
    - c[i]: Continuous, charging duration at charger node i
    - z[i]: Binary, truck charges at charger node i
    
    Constraints:
    - Delivery sequence ordering (visit deliveries in prescribed order)
    - Battery feasibility (battery never negative, bounded by capacity)
    - Charging dynamics (battery increases based on charger specs and duration)
    - Flow conservation (each delivery visited exactly once)
    """
    
    def __init__(self, env, config: dict, time_limit: int = 180, verbose: bool = True):
        """
        Initialize the Gurobi optimal planner.
        
        Args:
            env: EventDrivenTruckEnv instance (already reset with seed)
            config: Configuration dictionary
            time_limit: Gurobi time limit in seconds per truck
            verbose: Print detailed information
        """
        self.env = env
        self.config = config
        self.time_limit = time_limit
        self.verbose = verbose
        
        # Extract scenario parameters
        self.trucks = env.trucks
        self.num_trucks = len(self.trucks)
        self.graph = env.transport_graph
        self.charging_nodes = env.charging_nodes
        self.max_time = config["environment"]["max_time"]
        
        # Truck parameters
        self.battery_capacity = config["truck"]["battery_capacity"]
        self.base_speed = config["truck"]["base_speed"]
        
        # Charging parameters
        self.charging_config = config["charging"]
        
        # Big M for disjunctive constraints (smaller = tighter formulation)
        self.BIG_M = self.max_time * 2
        
        # Store individual truck models and solutions
        self.truck_models = {}
        self.truck_solutions = {}
        self.solution = None
        
    def build_model(self):
        """Build independent MILP models for each truck."""
        if self.verbose:
            print("\n" + "="*80)
            print("BUILDING GUROBI OPTIMIZATION MODELS (DECOMPOSED BY TRUCK)")
            print("="*80)
            print(f"Trucks: {self.num_trucks}")
            print(f"Charging nodes: {len(self.charging_nodes)}")
            print(f"Max time horizon: {self.max_time} hours")
            print(f"Solving each truck independently...")
        
        # Build a separate model for each truck
        for k in range(self.num_trucks):
            if self.verbose:
                print(f"\nBuilding model for Truck {k}...")
            self._build_single_truck_model(k)
        
        if self.verbose:
            total_vars = sum(m['model'].NumVars for m in self.truck_models.values())
            total_constrs = sum(m['model'].NumConstrs for m in self.truck_models.values())
            print(f"\nAll models built successfully!")
            print(f"Total variables (across all trucks): {total_vars}")
            print(f"Total constraints (across all trucks): {total_constrs}")
            print("="*80)
    
    def _build_single_truck_model(self, truck_idx: int):
        """Build optimization model for a single truck."""
        truck = self.trucks[truck_idx]
        
        # Node sets
        deliveries = truck.delivery_sequence[1:]
        start_node = truck.delivery_sequence[0]
        all_nodes = set([start_node] + deliveries + self.charging_nodes)
        nodes = sorted(list(all_nodes))
        
        if self.verbose:
            print(f"  Start: {start_node}")
            print(f"  Deliveries: {deliveries}")
            print(f"  Accessible nodes: {len(nodes)}")
        
        # Create model
        model = gp.Model(f"Truck_{truck_idx}")
        model.Params.TimeLimit = self.time_limit
        model.Params.MIPGap = 0.05  # Accept 5% optimality gap for speed
        model.Params.MIPFocus = 1  # Focus on finding feasible solutions quickly
        if not self.verbose:
            model.Params.OutputFlag = 0
        
        # Decision variables
        x = {}  # Routing variables
        t = {}  # Timing variables
        b = {}  # Battery variables
        c = {}  # Charging duration
        z = {}  # Charging indicator
        
        # Create routing variables for feasible arcs
        for i in nodes:
            for j in nodes:
                if i != j:
                    energy = self.graph.get_path_energy(i, j)
                    if energy < float('inf'):
                        x[i,j] = model.addVar(vtype=GRB.BINARY, name=f"x_{i}_{j}")
        
        # Create timing and battery variables
        for i in nodes:
            t[i] = model.addVar(lb=0, ub=self.max_time, vtype=GRB.CONTINUOUS, name=f"t_{i}")
            b[i] = model.addVar(lb=0, ub=self.battery_capacity, vtype=GRB.CONTINUOUS, name=f"b_{i}")
        
        # Charging variables (only at chargers)
        for i in self.charging_nodes:
            if i in nodes:
                c[i] = model.addVar(lb=0, ub=self.max_time, vtype=GRB.CONTINUOUS, name=f"c_{i}")
                z[i] = model.addVar(vtype=GRB.BINARY, name=f"z_{i}")
        
        # Completion time
        T_complete = model.addVar(lb=0, ub=self.max_time, vtype=GRB.CONTINUOUS, name="T_complete")
        
        model.update()
        
        # Add constraints
        self._add_single_truck_constraints(model, truck, truck_idx, nodes, deliveries, start_node,
                                          x, t, b, c, z, T_complete)
        
        # Set objective: minimize completion time
        model.setObjective(T_complete, GRB.MINIMIZE)
        
        # Store model and variables
        self.truck_models[truck_idx] = {
            'model': model,
            'truck': truck,
            'nodes': nodes,
            'deliveries': deliveries,
            'start': start_node,
            'vars': {'x': x, 't': t, 'b': b, 'c': c, 'z': z, 'T_complete': T_complete}
        }
        
        if self.verbose:
            print(f"  Variables: {model.NumVars}, Constraints: {model.NumConstrs}")
    
    def _add_single_truck_constraints(self, model, truck, truck_idx, nodes, deliveries, start, x, t, b, c, z, T_complete):
        """Add all constraints for a single truck model."""
        
        # 1. Delivery sequence constraints
        for d in deliveries:
            incoming = gp.LinExpr()
            for i in nodes:
                if i != d and (i,d) in x:
                    incoming += x[i,d]
            model.addConstr(incoming == 1, name=f"visit_{d}")
        
        # Start: one outgoing
        outgoing_start = gp.LinExpr()
        for j in nodes:
            if j != start and (start,j) in x:
                outgoing_start += x[start,j]
        model.addConstr(outgoing_start == 1, name="leave_start")
        
        # Flow conservation
        for i in nodes:
            if i == start:
                continue
            
            incoming = gp.LinExpr()
            outgoing = gp.LinExpr()
            
            for j in nodes:
                if j != i:
                    if (j,i) in x:
                        incoming += x[j,i]
                    if (i,j) in x:
                        outgoing += x[i,j]
            
            if i in deliveries:
                if i != deliveries[-1]:
                    model.addConstr(outgoing == 1, name=f"flow_{i}")
                else:
                    model.addConstr(outgoing == 0, name=f"flow_final_{i}")
            elif i in self.charging_nodes:
                model.addConstr(incoming == outgoing, name=f"flow_charger_{i}")
        
        # Delivery ordering
        for idx in range(len(deliveries) - 1):
            d1, d2 = deliveries[idx], deliveries[idx + 1]
            model.addConstr(t[d2] >= t[d1] + 0.01, name=f"order_{d1}_{d2}")
        
        # 2. Battery constraints (simplified - only for used arcs)
        model.addConstr(b[start] == truck.current_battery, name="initial_battery")
        
        # Simpler formulation: only enforce battery dynamics when arc is used
        for i in nodes:
            for j in nodes:
                if i != j and (i,j) in x:
                    energy = self.graph.get_path_energy(i, j)
                    
                    # Skip infeasible arcs (battery too low even with full charge)
                    if energy > self.battery_capacity:
                        continue
                    
                    if i in self.charging_nodes and i in c:
                        charge_amount = self._get_charge_amount_expr_single(i, c[i])
                        # Indicator constraint: if x[i,j]=1, then b[j] = b[i] + charge - energy
                        model.addConstr(
                            (x[i,j] == 1) >> (b[j] == b[i] + charge_amount - energy),
                            name=f"battery_{i}_{j}")
                    else:
                        model.addConstr(
                            (x[i,j] == 1) >> (b[j] == b[i] - energy),
                            name=f"battery_{i}_{j}_nc")
        
        for i in self.charging_nodes:
            if i in nodes and i in c:
                charge_amount = self._get_charge_amount_expr_single(i, c[i])
                model.addConstr(b[i] + charge_amount <= self.battery_capacity, name=f"battery_cap_{i}")
        
        # 3. Charging constraints
        for i in self.charging_nodes:
            if i in nodes and i in c:
                visiting = gp.LinExpr()
                for j in nodes:
                    if j != i and (j,i) in x:
                        visiting += x[j,i]
                
                model.addConstr(z[i] == visiting, name=f"charge_visit_{i}")
                model.addConstr(c[i] <= self.max_time * z[i], name=f"charge_duration_{i}")
                model.addConstr(c[i] >= 0.1 * z[i], name=f"min_charge_{i}")
        
        # 4. Time constraints (simplified with indicator constraints)
        model.addConstr(t[start] == 0, name="start_time")
        
        for i in nodes:
            for j in nodes:
                if i != j and (i,j) in x:
                    travel_time = self.graph.get_time_distance(i, j)
                    
                    if i in self.charging_nodes and i in c:
                        # Indicator: if x[i,j]=1, then t[j] >= t[i] + c[i] + travel_time
                        model.addConstr(
                            (x[i,j] == 1) >> (t[j] >= t[i] + c[i] + travel_time),
                            name=f"time_prop_{i}_{j}")
                    else:
                        model.addConstr(
                            (x[i,j] == 1) >> (t[j] >= t[i] + travel_time),
                            name=f"time_prop_{i}_{j}_nc")
        
        # Completion time
        last_delivery = deliveries[-1]
        model.addConstr(T_complete == t[last_delivery], name="completion_time")
    
    def _get_charge_amount_expr_single(self, charger_node: int, c_var) -> gp.LinExpr:
        """Get charge amount expression for single truck model."""
        charger_type = self.graph.get_charger_type(charger_node)
        if charger_type == "DCFast":
            charge_config = self.charging_config["dcfast"]
        else:
            charge_config = self.charging_config["level2"]
        
        charge_rate = charge_config["charge_rate"]
        efficiency = charge_config["efficiency"]
        return charge_rate * efficiency * c_var
    
    def _create_variables(self):
        """Create decision variables."""
        if self.verbose:
            print("\nCreating decision variables...")
        
        # Routing variables: x[i,j,k] = 1 if truck k goes from node i to j
        self.vars['x'] = {}
        for k in range(self.num_trucks):
            for i in self.truck_nodes[k]:
                for j in self.truck_nodes[k]:
                    if i != j:
                        # Only create arc if path exists
                        energy = self.graph.get_path_energy(i, j)
                        if energy < float('inf'):
                            self.vars['x'][i,j,k] = self.model.addVar(
                                vtype=GRB.BINARY, 
                                name=f"x_{i}_{j}_{k}"
                            )
        
        # Timing variables: t[i,k] = arrival time of truck k at node i
        self.vars['t'] = {}
        for k in range(self.num_trucks):
            for i in self.truck_nodes[k]:
                self.vars['t'][i,k] = self.model.addVar(
                    lb=0, ub=self.max_time,
                    vtype=GRB.CONTINUOUS,
                    name=f"t_{i}_{k}"
                )
        
        # Battery variables: b[i,k] = battery level upon arrival at node i
        self.vars['b'] = {}
        for k in range(self.num_trucks):
            for i in self.truck_nodes[k]:
                self.vars['b'][i,k] = self.model.addVar(
                    lb=0, ub=self.battery_capacity,
                    vtype=GRB.CONTINUOUS,
                    name=f"b_{i}_{k}"
                )
        
        # Charging duration: c[i,k] = hours charged at node i by truck k
        self.vars['c'] = {}
        for k in range(self.num_trucks):
            for i in self.charging_nodes:
                if i in self.truck_nodes[k]:
                    self.vars['c'][i,k] = self.model.addVar(
                        lb=0, ub=self.max_time,
                        vtype=GRB.CONTINUOUS,
                        name=f"c_{i}_{k}"
                    )
        
        # Charging indicator: z[i,k] = 1 if truck k charges at node i
        self.vars['z'] = {}
        for k in range(self.num_trucks):
            for i in self.charging_nodes:
                if i in self.truck_nodes[k]:
                    self.vars['z'][i,k] = self.model.addVar(
                        vtype=GRB.BINARY,
                        name=f"z_{i}_{k}"
                    )
        
        # Completion time for each truck
        self.vars['T_complete'] = {}
        for k in range(self.num_trucks):
            self.vars['T_complete'][k] = self.model.addVar(
                lb=0, ub=self.max_time,
                vtype=GRB.CONTINUOUS,
                name=f"T_complete_{k}"
            )
        
        # Makespan (max completion time)
        self.vars['makespan'] = self.model.addVar(
            lb=0, ub=self.max_time,
            vtype=GRB.CONTINUOUS,
            name="makespan"
        )
        
        self.model.update()
        
        if self.verbose:
            print(f"  Routing variables (x): {len(self.vars['x'])}")
            print(f"  Timing variables (t): {len(self.vars['t'])}")
            print(f"  Battery variables (b): {len(self.vars['b'])}")
            print(f"  Charging duration (c): {len(self.vars['c'])}")
            print(f"  Charging indicators (z): {len(self.vars['z'])}")
    
    def _add_delivery_sequence_constraints(self):
        """Ensure trucks visit deliveries in prescribed order."""
        if self.verbose:
            print("\nAdding delivery sequence constraints...")
        
        for k, truck in enumerate(self.trucks):
            deliveries = self.truck_deliveries[k]
            start = self.truck_start[k]
            
            # Each delivery must be visited exactly once (one incoming arc)
            for d in deliveries:
                incoming = gp.LinExpr()
                for i in self.truck_nodes[k]:
                    if i != d and (i,d,k) in self.vars['x']:
                        incoming += self.vars['x'][i,d,k]
                self.model.addConstr(incoming == 1, name=f"visit_delivery_{d}_truck_{k}")
            
            # Start node: exactly one outgoing arc
            outgoing_start = gp.LinExpr()
            for j in self.truck_nodes[k]:
                if j != start and (start,j,k) in self.vars['x']:
                    outgoing_start += self.vars['x'][start,j,k]
            self.model.addConstr(outgoing_start == 1, name=f"leave_start_{k}")
            
            # Flow conservation: if truck enters a node (delivery or charger), it must leave
            # This applies to all nodes except start and final delivery
            for i in self.truck_nodes[k]:
                if i == start:
                    continue  # Start only has outgoing
                
                incoming = gp.LinExpr()
                outgoing = gp.LinExpr()
                
                for j in self.truck_nodes[k]:
                    if j != i:
                        if (j,i,k) in self.vars['x']:
                            incoming += self.vars['x'][j,i,k]
                        if (i,j,k) in self.vars['x']:
                            outgoing += self.vars['x'][i,j,k]
                
                # Deliveries: incoming = 1 (enforced above), outgoing = 1 unless last delivery
                if i in deliveries:
                    if i != deliveries[-1]:  # Not the last delivery
                        self.model.addConstr(outgoing == 1, name=f"flow_{i}_{k}")
                    else:  # Last delivery: no outgoing required
                        self.model.addConstr(outgoing == 0, name=f"flow_final_{i}_{k}")
                        
                # Chargers: optional visit, but if visited then incoming = outgoing
                elif i in self.charging_nodes:
                    self.model.addConstr(incoming == outgoing, name=f"flow_charger_{i}_{k}")
            
            # Subtour elimination using time ordering for deliveries
            for idx in range(len(deliveries) - 1):
                d1 = deliveries[idx]
                d2 = deliveries[idx + 1]
                # d2 must be visited after d1
                self.model.addConstr(
                    self.vars['t'][d2,k] >= self.vars['t'][d1,k] + 0.01,
                    name=f"order_{d1}_before_{d2}_truck_{k}"
                )
    
    def _add_battery_constraints(self):
        """Add battery feasibility constraints."""
        if self.verbose:
            print("Adding battery feasibility constraints...")
        
        for k, truck in enumerate(self.trucks):
            start = self.truck_start[k]
            
            # Initial battery at start
            initial_battery = truck.current_battery
            self.model.addConstr(
                self.vars['b'][start,k] == initial_battery,
                name=f"initial_battery_{k}"
            )
            
            # Battery dynamics along arcs
            for i in self.truck_nodes[k]:
                for j in self.truck_nodes[k]:
                    if i != j and (i,j,k) in self.vars['x']:
                        energy = self.graph.get_path_energy(i, j)
                        
                        # If arc is used, battery at j = battery at i + charging at i - energy consumed
                        # Using big-M formulation
                        x_ij = self.vars['x'][i,j,k]
                        b_i = self.vars['b'][i,k]
                        b_j = self.vars['b'][j,k]
                        
                        # Get charging at i (0 if not a charger)
                        if i in self.charging_nodes and (i,k) in self.vars['c']:
                            charge_amount = self._get_charge_amount_expr(i, k)
                            
                            # If x[i,j,k] = 1: b[j,k] = b[i,k] + charge_amount - energy
                            self.model.addConstr(
                                b_j >= b_i + charge_amount - energy - self.BIG_M * (1 - x_ij),
                                name=f"battery_lb_{i}_{j}_{k}"
                            )
                            self.model.addConstr(
                                b_j <= b_i + charge_amount - energy + self.BIG_M * (1 - x_ij),
                                name=f"battery_ub_{i}_{j}_{k}"
                            )
                        else:
                            # No charging at i
                            self.model.addConstr(
                                b_j >= b_i - energy - self.BIG_M * (1 - x_ij),
                                name=f"battery_lb_{i}_{j}_{k}_nocharge"
                            )
                            self.model.addConstr(
                                b_j <= b_i - energy + self.BIG_M * (1 - x_ij),
                                name=f"battery_ub_{i}_{j}_{k}_nocharge"
                            )
            
            # Battery must be non-negative after any arc (already enforced by lb=0)
            # Battery cannot exceed capacity after charging
            for i in self.charging_nodes:
                if i in self.truck_nodes[k] and (i,k) in self.vars['c']:
                    charge_amount = self._get_charge_amount_expr(i, k)
                    self.model.addConstr(
                        self.vars['b'][i,k] + charge_amount <= self.battery_capacity,
                        name=f"battery_cap_{i}_{k}"
                    )
    
    def _get_charge_amount_expr(self, charger_node: int, truck_idx: int) -> gp.LinExpr:
        """
        Get expression for charge amount at a charger node.
        
        Args:
            charger_node: Charger node ID
            truck_idx: Truck index
            
        Returns:
            Gurobi linear expression for charge amount (kWh)
        """
        charger_type = self.graph.get_charger_type(charger_node)
        
        if charger_type == "DCFast":
            charge_config = self.charging_config["dcfast"]
        else:
            charge_config = self.charging_config["level2"]
        
        charge_rate = charge_config["charge_rate"]  # kW
        efficiency = charge_config["efficiency"]
        
        # Charge amount = charge_rate * efficiency * duration
        return charge_rate * efficiency * self.vars['c'][charger_node, truck_idx]
    
    def _add_charging_constraints(self):
        """Add charging-related constraints."""
        if self.verbose:
            print("Adding charging constraints...")
        
        for k in range(self.num_trucks):
            for i in self.charging_nodes:
                if i in self.truck_nodes[k] and (i,k) in self.vars['c']:
                    # Charging only happens if truck visits the charger
                    # z[i,k] = 1 if truck k visits charger i
                    visiting = gp.LinExpr()
                    for j in self.truck_nodes[k]:
                        if j != i and (j,i,k) in self.vars['x']:
                            visiting += self.vars['x'][j,i,k]
                    
                    # z[i,k] = 1 iff truck visits charger i
                    self.model.addConstr(
                        self.vars['z'][i,k] == visiting,
                        name=f"charge_visit_{i}_{k}"
                    )
                    
                    # Charging duration > 0 only if z[i,k] = 1
                    self.model.addConstr(
                        self.vars['c'][i,k] <= self.max_time * self.vars['z'][i,k],
                        name=f"charge_duration_{i}_{k}"
                    )
                    
                    # Minimum charging duration (if charging at all): 0.1 hours
                    self.model.addConstr(
                        self.vars['c'][i,k] >= 0.1 * self.vars['z'][i,k],
                        name=f"min_charge_{i}_{k}"
                    )
    
    def _add_flow_constraints(self):
        """Add flow conservation constraints."""
        if self.verbose:
            print("Adding flow conservation constraints...")
        
        # Already handled in delivery sequence constraints
        pass
    
    def _add_time_constraints(self):
        """Add timing constraints."""
        if self.verbose:
            print("Adding time constraints...")
        
        for k, truck in enumerate(self.trucks):
            start = self.truck_start[k]
            
            # Start time is 0
            self.model.addConstr(
                self.vars['t'][start,k] == 0,
                name=f"start_time_{k}"
            )
            
            # Time propagation along arcs
            for i in self.truck_nodes[k]:
                for j in self.truck_nodes[k]:
                    if i != j and (i,j,k) in self.vars['x']:
                        travel_time = self.graph.get_time_distance(i, j)
                        x_ij = self.vars['x'][i,j,k]
                        t_i = self.vars['t'][i,k]
                        t_j = self.vars['t'][j,k]
                        
                        # Charging time at i (if charger)
                        if i in self.charging_nodes and (i,k) in self.vars['c']:
                            c_i = self.vars['c'][i,k]
                            # If x[i,j,k] = 1: t[j,k] >= t[i,k] + c[i,k] + travel_time
                            self.model.addConstr(
                                t_j >= t_i + c_i + travel_time - self.BIG_M * (1 - x_ij),
                                name=f"time_prop_{i}_{j}_{k}"
                            )
                        else:
                            # No charging at i
                            self.model.addConstr(
                                t_j >= t_i + travel_time - self.BIG_M * (1 - x_ij),
                                name=f"time_prop_{i}_{j}_{k}_nocharge"
                            )
            
            # Completion time = time at last delivery
            last_delivery = self.truck_deliveries[k][-1]
            self.model.addConstr(
                self.vars['T_complete'][k] == self.vars['t'][last_delivery,k],
                name=f"completion_time_{k}"
            )
            
            # Makespan >= completion time of all trucks
            self.model.addConstr(
                self.vars['makespan'] >= self.vars['T_complete'][k],
                name=f"makespan_{k}"
            )
    
    def _add_charger_capacity_constraints(self):
        """
        Add charger capacity constraints (simplified - no explicit queue modeling).
        
        This is a simplified version that doesn't model detailed queuing.
        We ensure that no more than C trucks charge simultaneously at any charger.
        
        For a more accurate model, we would need time-indexed variables.
        """
        if self.verbose:
            print("Adding charger capacity constraints (simplified)...")
        
        # Simplified: limit total number of trucks that can charge at each station
        # This is conservative but tractable
        for i in self.charging_nodes:
            capacity = int(self.graph.get_charger_capacity(i))
            
            # Total trucks charging at this station <= capacity
            # (This is a relaxation - doesn't enforce temporal overlap)
            total_charging = gp.LinExpr()
            for k in range(self.num_trucks):
                if i in self.truck_nodes[k] and (i,k) in self.vars['z']:
                    total_charging += self.vars['z'][i,k]
            
            self.model.addConstr(
                total_charging <= capacity,
                name=f"charger_capacity_{i}"
            )
    
    def _set_objective(self):
        """Set the optimization objective."""
        if self.verbose:
            print("Setting objective function...")
        
        # Objective: minimize total time (sum of all truck completion times)
        # Alternative: minimize makespan (max completion time)
        
        # Option 1: Total time
        total_time = gp.quicksum(self.vars['T_complete'][k] for k in range(self.num_trucks))
        
        # Option 2: Makespan (enable this for min-max objective)
        # obj = self.vars['makespan']
        
        # Use total time as primary objective, makespan as secondary
        obj = total_time + 0.1 * self.vars['makespan']
        
        self.model.setObjective(obj, GRB.MINIMIZE)
        
        if self.verbose:
            print("Objective: Minimize total completion time across all trucks")
    
    def solve(self) -> bool:
        """
        Solve the optimization problem for all trucks independently.
        
        Returns:
            True if all trucks found optimal/feasible solution, False otherwise
        """
        if self.verbose:
            print("\n" + "="*80)
            print("SOLVING OPTIMIZATION PROBLEMS")
            print("="*80)
        
        all_success = True
        total_time = 0
        
        for k in range(self.num_trucks):
            if self.verbose:
                print(f"\nSolving Truck {k}...")
            
            model_data = self.truck_models[k]
            model = model_data['model']
            
            model.optimize()
            status = model.Status
            
            if status == GRB.OPTIMAL:
                if self.verbose:
                    print(f"  ✓ Optimal solution found!")
                    print(f"  Objective: {model.ObjVal:.2f}h")
                    print(f"  Solve time: {model.Runtime:.2f}s")
                self._extract_single_truck_solution(k)
                total_time += model.Runtime
                
            elif status == GRB.TIME_LIMIT and model.SolCount > 0:
                if self.verbose:
                    print(f"  ⚠ Time limit reached, feasible solution found")
                    print(f"  Objective: {model.ObjVal:.2f}h")
                    print(f"  Gap: {model.MIPGap*100:.2f}%")
                self._extract_single_truck_solution(k)
                total_time += model.Runtime
                
            elif status == GRB.INFEASIBLE:
                if self.verbose:
                    print(f"  ✗ Model infeasible")
                    print(f"  Computing IIS...")
                    model.computeIIS()
                    model.write(f"truck_{k}_iis.ilp")
                    print(f"  IIS written to truck_{k}_iis.ilp")
                all_success = False
                
            else:
                if self.verbose:
                    print(f"  ✗ Optimization failed with status {status}")
                all_success = False
        
        if all_success:
            self._combine_solutions()
            if self.verbose:
                print(f"\n{'='*80}")
                print(f"✓ All trucks solved successfully!")
                print(f"Total solve time: {total_time:.2f}s")
                print(f"{'='*80}")
        else:
            if self.verbose:
                print(f"\n{'='*80}")
                print(f"✗ Some trucks failed to solve")
                print(f"{'='*80}")
        
        return all_success
    
    def _extract_single_truck_solution(self, truck_idx: int):
        """Extract solution for a single truck."""
        model_data = self.truck_models[truck_idx]
        vars = model_data['vars']
        nodes = model_data['nodes']
        deliveries = model_data['deliveries']
        start = model_data['start']
        x = vars['x']
        t = vars['t']
        b = vars['b']
        c = vars['c']
        
        # Extract route
        route = [start]
        current = start
        visited = set([current])
        max_iterations = len(nodes)
        iterations = 0
        
        while iterations < max_iterations:
            iterations += 1
            found_next = False
            
            for j in nodes:
                if j != current and (current,j) in x:
                    if x[current,j].X > 0.5:
                        route.append(j)
                        visited.add(j)
                        current = j
                        found_next = True
                        break
            
            if not found_next or all(d in visited for d in deliveries):
                break
        
        # Extract charging
        charging = {}
        for i in self.charging_nodes:
            if i in route and i in c:
                duration = c[i].X
                if duration > 0.01:
                    charging[i] = {
                        'duration': duration,
                        'arrival_time': t[i].X,
                        'battery_on_arrival': b[i].X,
                    }
        
        # Extract timing
        timing = {}
        for i in route:
            timing[i] = {
                'arrival_time': t[i].X,
                'battery': b[i].X,
            }
        
        # Store solution
        self.truck_solutions[truck_idx] = {
            'route': route,
            'charging': charging,
            'timing': timing,
            'completion_time': vars['T_complete'].X
        }
    
    def _combine_solutions(self):
        """Combine individual truck solutions into overall solution."""
        self.solution = {
            'routes': {},
            'charging': {},
            'timing': {},
            'objective': sum(s['completion_time'] for s in self.truck_solutions.values()),
            'makespan': max(s['completion_time'] for s in self.truck_solutions.values()),
        }
        
        for k, sol in self.truck_solutions.items():
            self.solution['routes'][k] = sol['route']
            self.solution['charging'][k] = sol['charging']
            self.solution['timing'][k] = sol['timing']
    
    def get_action_sequence(self) -> Dict[int, List[Tuple[str, int, float]]]:
        """
        Convert solution to action sequences for each truck.
        
        Returns:
            Dictionary mapping truck_id to list of (action_type, node, param) tuples
            action_type: 'navigate' or 'charge'
            node: destination node for navigate, charger node for charge
            param: None for navigate, charging duration for charge
        """
        if self.solution is None:
            raise ValueError("No solution available. Call solve() first.")
        
        actions = {}
        
        for k in range(self.num_trucks):
            truck_actions = []
            route = self.solution['routes'][k]
            charging = self.solution['charging'][k]
            
            for idx in range(len(route) - 1):
                current = route[idx]
                next_node = route[idx + 1]
                
                # Navigate to next node
                truck_actions.append(('navigate', next_node, None))
                
                # Check if charging at next node
                if next_node in charging:
                    duration = charging[next_node]['duration']
                    truck_actions.append(('charge', next_node, duration))
            
            actions[k] = truck_actions
        
        return actions
    
    def validate_solution(self, env) -> Tuple[bool, str]:
        """
        Validate solution by simulating through environment.
        
        Args:
            env: Fresh environment instance (reset with same seed)
            
        Returns:
            Tuple of (is_valid, message)
        """
        if self.solution is None:
            return False, "No solution to validate"
        
        if self.verbose:
            print("\n" + "="*80)
            print("VALIDATING SOLUTION")
            print("="*80)
        
        # This is a simplified validation - checks route feasibility
        for k in range(self.num_trucks):
            route = self.solution['routes'][k]
            truck = self.trucks[k]
            deliveries = truck.delivery_sequence[1:]  # Expected deliveries
            
            # Check all deliveries are visited
            if not all(d in route for d in deliveries):
                return False, f"Truck {k}: Not all deliveries visited"
            
            # Check delivery order
            delivery_positions = [route.index(d) for d in deliveries]
            if delivery_positions != sorted(delivery_positions):
                return False, f"Truck {k}: Deliveries not in correct order"
            
            # Check battery feasibility (simplified)
            battery = self.trucks[k].current_battery
            charging = self.solution['charging'][k]
            
            for idx in range(len(route) - 1):
                current = route[idx]
                next_node = route[idx + 1]
                
                # Check if path exists
                energy = self.graph.get_path_energy(current, next_node)
                if energy == float('inf'):
                    return False, f"Truck {k}: No path from {current} to {next_node}"
                
                # Apply charging if at charger
                if current in charging:
                    charge_amount = self._compute_charge_amount(
                        current, charging[current]['duration']
                    )
                    battery = min(self.battery_capacity, battery + charge_amount)
                
                # Consume energy
                battery -= energy
                
                if battery < -0.01:  # Small tolerance
                    return False, f"Truck {k}: Battery depleted between {current} and {next_node}"
        
        if self.verbose:
            print("✓ Solution is valid!")
        
        return True, "Solution is valid"
    
    def _compute_charge_amount(self, charger_node: int, duration: float) -> float:
        """Compute charge amount for given duration at charger."""
        charger_type = self.graph.get_charger_type(charger_node)
        
        if charger_type == "DCFast":
            charge_config = self.charging_config["dcfast"]
        else:
            charge_config = self.charging_config["level2"]
        
        charge_rate = charge_config["charge_rate"]
        efficiency = charge_config["efficiency"]
        
        return charge_rate * efficiency * duration
    
    def print_solution_summary(self):
        """Print a summary of the solution."""
        if self.solution is None:
            print("No solution available")
            return
        
        print("\n" + "="*80)
        print("SOLUTION SUMMARY")
        print("="*80)
        
        print(f"\nTotal completion time (sum): {self.solution['objective']:.2f} hours")
        print(f"Makespan (max): {self.solution['makespan']:.2f} hours")
        
        total_charging_time = 0
        total_charging_sessions = 0
        
        for k in range(self.num_trucks):
            sol = self.truck_solutions[k]
            print(f"\n{'─'*80}")
            print(f"Truck {k}:")
            print(f"{'─'*80}")
            
            route = sol['route']
            charging = sol['charging']
            timing = sol['timing']
            
            print(f"Route: {' → '.join(map(str, route))}")
            print(f"Completion time: {sol['completion_time']:.2f} hours")
            
            if charging:
                print(f"\nCharging sessions: {len(charging)}")
                for node, info in charging.items():
                    print(f"  • Node {node}:")
                    print(f"      Arrival: t={info['arrival_time']:.2f}h, Battery={info['battery_on_arrival']:.1f} kWh")
                    print(f"      Duration: {info['duration']:.2f} hours")
                    charge_amount = self._compute_charge_amount(node, info['duration'])
                    print(f"      Charged: {charge_amount:.1f} kWh")
                    
                    total_charging_time += info['duration']
                    total_charging_sessions += 1
            else:
                print(f"\nNo charging required")
            
            # Print battery trajectory
            print(f"\nBattery trajectory:")
            for node in route:
                if node in timing:
                    print(f"  Node {node}: {timing[node]['battery']:.1f} kWh at t={timing[node]['arrival_time']:.2f}h")
        
        print(f"\n{'='*80}")
        print(f"Total charging time (all trucks): {total_charging_time:.2f} hours")
        print(f"Total charging sessions: {total_charging_sessions}")
        print("="*80)
